
service: serverless-fastapi-mangum-alb

plugins:
  - serverless-python-requirements

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

  stage: dev
  region: ap-northeast-1

functions:
  hello:
    handler: handler.handler
    events:
      - alb:
          listenerArn: ${env:LISTER_ARN}
          priority: 1
          conditions:
            # host: example.com
            path: /
